name: basic-test
on: [push]
jobs:
  test:
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'sunpy/sunpy'
      - run: python3 -m venv venv
      - run: . venv/bin/activate
      - run: python3 -m pip install "tox<4"
      - run: python3 -m tox -e py310
