name: basic-test
on: [push]
jobs:
  build_and_publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs mypackage
      targets: |
        - cp311-manylinux_x86_64
        - cp312-manylinux_x86_64
      env: |
        CIBW_ENVIRONMENT: '$(if [ "$(echo "$GITHUB_JOB" | cut -c7-17)" = "cp312" ]; then PIP_PRE=1; else PIP_PRE=0; fi)'
