name: basic-test
on: [push]
jobs:
  build_and_publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs mypackage
      targets: |
        - cp311-manylinux_x86_64
        - cp312-manylinux_x86_64
      env: |
        CIBW_ENVIRONMENT: 'PIP_PRE=$(if echo "$GITHUB_JOB" | grep -q "cp312"; then echo 1; else echo 0; fi)'
