name: basic-test
on: [push]
jobs:
  test:
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'sunpy/sunpy'
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
