name: basic-test
on: [push]
jobs:
  test:
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -c "print('hello world!')"
